version: '3.0'
services:
  gluetun-sm:
    image: qmcgaw/gluetun
    container_name: gluetun-sm
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - dotenv.gluetun
  stock-checker:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "service:gluetun-sm"
    container_name: stock-checker
    env_file:
      - dotenv
