version: '3.0'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080
      - 8081:8081
    env_file:
      - dotenv.gluetun
  stock-checker:
    image: docker.io/jayyzhao/stock-checker:v1.0.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: stock-checker
    env_file:
      - dotenv
