version: '3.0'
services:
  stock-checker:
    image: docker.io/jayyzhao/stock-checker:v1.0.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: stock-checker
    env_file:
      - dotenv
